defaultAirflowTag: 2.10.5

# executor: CeleryKubernetesExecutor
executor: KubernetesExecutor

workers:
  replicas: 1

webserverSecretKey: UldqVEJKU25sSHBKb0xQTk9NTU9XQUt3U2JTeEhacnE=
fernetKey: eWRVaXJ5SmhrY1cwNUJuRnNmZ25UbG9nMGc2OVM3bm8=

redis:
  password: MgRJ6HVoCs

# logs:
#   persistence:
#     enabled: true

config:
  # configure logging to s3 using the remote logging feature
  logging:
    remote_logging: 'True'
    logging_level: 'INFO'
    remote_base_log_folder: 's3://logs'   # Specify the S3 bucket
    remote_log_conn_id: 'logs'            # Specify the Amazon Web Service connection
    delete_worker_pods: 'False'
    encrypt_s3_logs: 'False'
  metrics:
    # disable statsd metrics warning when running python scriptsS
    metrics_use_pattern_match: 'True'
